name: CI — Build, Test, Package

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read
  packages: write

env:
  FRONTEND_DIR: frontend
  CHART_DIR: helm/aiagent
  WEB_IMAGE: ${{ secrets.DOCKER_REGISTRY }}/aiagent_web:${{ github.sha }}
  WORKER_IMAGE: ${{ secrets.DOCKER_REGISTRY }}/aiagent_worker:${{ github.sha }}

jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install frontend deps & run unit tests
        working-directory: ${{ env.FRONTEND_DIR }}
        run: |
          npm ci
          npm run test --if-present

      - name: Run basic shellcheck on scripts
        run: |
          sudo apt-get update -y
          sudo apt-get install -y shellcheck
          find . -name '*.sh' -not -path "./node_modules/*" -print0 | xargs -0 shellcheck -s bash || true

  build-and-push:
    name: Build & Push Docker images + Package Helm
    runs-on: ubuntu-latest
    needs: lint-and-test
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU (for cross-arch if needed)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_HOST }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push web image
        run: |
          docker build -f Dockerfile -t "${{ env.WEB_IMAGE }}" .
          docker push "${{ env.WEB_IMAGE }}"

      - name: Build & push worker image (if Dockerfile.worker exists)
        run: |
          if [ -f Dockerfile.worker ]; then
            docker build -f Dockerfile.worker -t "${{ env.WORKER_IMAGE }}" .
            docker push "${{ env.WORKER_IMAGE }}"
          else
            echo "No Dockerfile.worker found; skipping worker image"
          fi

      - name: Package Helm chart
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Lint Helm chart
        run: |
          helm lint ${{ env.CHART_DIR }}

      - name: Package and upload Helm chart artifact
        run: |
          mkdir -p build
          helm package ${{ env.CHART_DIR }} -d build
          ls -la build
        # store chart artifact for CD job
      - name: Upload chart artifact
        uses: actions/upload-artifact@v4
        with:
          name: aiagent-helm-chart
          path: build/*.tgz

