name: Chaos Test
title: "[CHAOS] <failure scenario>"
labels: ["chaos", "resilience"]
body:
  - type: input
    id: component
    attributes:
      label: Target Component
      placeholder: "worker / db / step-runner"
    validations:
      required: true

  - type: textarea
    id: failure
    attributes:
      label: Failure Injected
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected System Behavior
    validations:
      required: true

  - type: textarea
    id: metrics
    attributes:
      label: Metrics & Alerts Triggered
    validations:
      required: true
