{{- if .Values.imagePullSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ (index .Values.imagePullSecrets 0).name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ""
{{- end }}

